# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMpQX-62Dc84lgKw65uJE-b6m7lW1GYn
"""

numbers=[]
count=5
while len(numbers)< count :
  x=int(input("Enter numbers: \n"))

  if x< 0:
    print("Enter a postive number")
  else:
    numbers.append(x)

print("the avarge is",sum(numbers)/len(numbers))

even_postivie=0
odd_postivie=0
even_negative=0
odd_negative=0

while True:
  x=int(input("Enter a number:"))

  if x == 0:
    break 
  elif x>0 and x%2==0:
    even_postivie +=1
  elif x>0 and x%2 !=0:
    odd_postivie +=1
  elif x<0 and x%2==0:
    even_negative +=1
  elif x<0 and x%2 !=0:
    odd_negative +=1

print("The even postive numbers =",even_postivie)
print("The odd postive numbers =",odd_postivie)
print("The even negative numbers =",even_negative)
print("The odd negative numbers =",odd_negative)