# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ziOCJF2kz9-Mx3-EgqDFa3uNjX0lzk0
"""

def print_numbers(n):
  if n%3==0 and n%5==0:
      print("FizzBuzz")
  elif n%3==0:
      print("Fizz")
  elif n%5==0:
      print("Buzz")
  else:
      print(n)

print_numbers(15)

def is_prime(x):
  if x <= 1:
    return False
  for i in range(2, int(x ** 0.5) + 1):
    if x % i == 0:
      return False
  return True



for i in range(2, 100):
  if is_prime(i):
    print(i,end="\t")

def union(list1,list2):
  l=[]
  for i in list1 and list2:
    if i not in l:
      l.append(i)

  return l


union([1,2,3,2],[2,4,3])

def flatten(list1):
  result = []
  for i in list1:
    for j in i:
      result.append(j)
  return result


flatten([[1,2,3,2],[2,4,3]])



def prefix(list1, list2):
  result=[]
  for i in range(len(list1)):
    if list1[i]==list2[i]:
      result.append(i)
      return True
    else:
      return False

prefix([1, 2, 2, 3], [1, 2, 3, 4])